backend:
  name: github
  repo: bdougie/blog # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "source/img/uploads" # Folder where user uploaded files should go
public_folder: "source" # CMS now knows 'source' is the public folder and will strip this from the path

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "source/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post-layout"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
